### ISSUE TITLE
More Github Data for Contributors

### ISSUE THREAD

**Issue by seveibar** [tscircuit/contribution-tracker#5]
Generate a new table "Review Table" in the contributor overview that shows:

- The number of REVIEWS RECEIVED
- The number of REVIEWS THE AUTHOR ASKED FOR
- The number of REVIEWS GIVEN
- The number of CHANGES REQUESTED ON PRS THE PERSON OPENED
- The number of PRS OPENED
- The number of PRS CLOSED

e.g.

| Username | Reviews Received | Reviews Requested | Reviews Given | Changes Requested | PRs Opened | PRs Closed |
|----------|-----------------|------------------|---------------|------------------|------------|------------|
| alice    | 45             | 52               | 38            | 12               | 28         | 25         |
| bob      | 32             | 35               | 41            | 8                | 19         | 17         |
| carol    | 28             | 30               | 25            | 5                | 15         | 14         |
| david    | 15             | 18               | 22            | 3                | 12         | 10         |

This table shows:
- **Reviews Received**: Total number of reviews received on their PRs
- **Reviews Requested**: Number of times the author explicitly requested reviews
- **Reviews Given**: Number of reviews they provided on others' PRs
- **Changes Requested**: Number of times changes were requested on their PRs
- **PRs Opened**: Total number of PRs they opened
- **PRs Closed**: Total number of their PRs that were closed

---

The code should run as part of the regular contribution generation scripts

/bounty $30

**Comment by kom-senapati** [comment]
/attempt #5 Adding params in PR, aggregating them and creating a review table
